### ISSUE TITLE
Thiết kế phần lưới nhập sản phẩm rộng hơn, giảm đường viền không cần thiết.

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#11]
![image](https://user-images.githubusercontent.com/47171247/54421915-fcb8ec00-473f-11e9-8164-521b5d5125c0.png)

Điều chỉnh được độ rộng cột, xóa nút tăng và giảm số lượng, thu nhỏ icon xóa và giảm, thu nhỏ size chữ, hoặc cho phạm bị hiển thị chữ to hơn, bỏ phần viền, chữ “Mã sản phẩm” để 2 dòng thôi, giá tiền có thể bỏ bớt 3 số không ở cuối

**Comment by ntxuan** [comment]
Hi Anh Toàn ,

- Bản mới em đã cập nhật.
