### ISSUE TITLE
8.	Thu nhỏ hoặc ẩn lun 2 thanh này càng tốt

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#14]
Thu nhỏ bớt phần khung ở trên và dưới form nhập
![image](https://user-images.githubusercontent.com/47171247/54422224-91234e80-4740-11e9-9ceb-d15a9828181c.png)

![image](https://user-images.githubusercontent.com/47171247/54422234-96809900-4740-11e9-9025-88bb045bfd8a.png)

**Comment by ntxuan** [comment]
Đã có
