### ISSUE TITLE
10.	Report:

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#16]
* Ngày nhận: lấy mặc định từ 01/10 của niên vụ hiện tại. VD: hiện tại là niên vụ 2018-2019 thì “ngày nhận từ” cho giá trị mặc định là: 01/10/2018
** Thống kê hóa đơn:
- Font chữ cho to hơn xíu. Time new roman (12)
- Ngày hiển thị định dạng: dd/mm/yy
- Thay cột “Loại bảng kê” -> Số TT
- Cho phép nhập tên khách hàng để tìm (không dùng list box mà dùng text box)
- Hiển thị thanh trược ngang và dọc

* 11.	Mục Mặt hàng Cấp 1: không hiển thị đầy đủ Cấp 1 đã nhập (đang chỉ có Phát Thành và Hoàng Dũng)
![image](https://user-images.githubusercontent.com/47171247/54422341-d8a9da80-4740-11e9-8c53-b77d6f347279.png)

**Comment by ntxuan** [comment]
Done
