### ISSUE TITLE
Hộp thoại cảnh báo dữ liệu trùng lập đã nhập

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#17]
Hiện tại dữ liệu không trùng lập cũng bị cảnh báo, mình fix lại chỗ này giúp em là:
*Điều kiện để cảnh báo trùng lập là khi kết 4 dữ liệu này lại với nhau nếu bị trùng với dữ liệu đã nhập thì mới hiện ra hộp thoại thông báo:
 -Mã sản phẩm
 -Số lượng
 -Mã khách hàng
 -Ngày nhận hàng

**Comment by tttoan** [comment]
Done
