### ISSUE TITLE
Lỗi hình ảnh

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#18]
Khi bắt đầu sử dụng phần mềm, kể từ hình thứ 2 sẽ bị đổi màu, anh khách phục giúp em tại vì có những hình bị đổi màu sẽ gây khó khăn cho việc xem thông tin trong hình.

**Comment by tttoan** [comment]
Hi em, check lại xem hình gốc có bị gì không nhé, anh đâu có xử lý gì hình đâu
