### ISSUE TITLE
Pending List: Capture

### ISSUE THREAD

**Issue by tttoan** [3t-opensources/DongXanh#2]
1. Lookup customer + customer level1 sai
2. Input Ngày nhận toa + Ngày nhận hàng => change to textfield format ddMMyyyy
3. Ngày nhận toa + Ngày nhận hàng => load value default, lay gia tri khi get job field: created_time
4. Save them don gia san pham
5. Field don gia + thanh tien => them dau ngan cach hang nghin vd 20,000,000
6. Phim tat Zoom in/out, xuay hinh
7. Message yes/no khi back tab hoac close tab
8. Button: Xoa toa/bang ke => rename: Xoa toa/bang ke(Alt + D)
9. Button: Luu toa/bang ke => rename: Luu toa/bang ke(Alt + S)
10. Table: phim tat len + xuong, vd Shift + up/down
11.Update don gia san pham

**Comment by tttoan** [comment]
4.Save them don gia san pham => done
11.Update don gia san pham => done

**Comment by ntxuan** [comment]
2.Input Ngày nhận toa + Ngày nhận hàng => change to textfield format ddMMyyyy
8.Button: Xoa toa/bang ke => rename: Xoa toa/bang ke(Alt + D)
9.Button: Luu toa/bang ke => rename: Luu toa/bang ke(Alt + S)

**Comment by tttoan** [comment]
nội dung cập nhật ngày 14/01/2019

**Comment by tttoan** [comment]
[YeuCauCapNhat-14012019.zip](https://github.com/3t-opensources/DongXanh/files/2755651/YeuCauCapNhat-14012019.zip)

**Comment by tttoan** [comment]
Done
