### ISSUE TITLE
Không xóa được toa nhập sai trong phần Thống kê hóa đơn

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#20]
Em bấm double vào 1 dòng thì lúc thì nó chỉ hiện ra hình, lúc thì nó cho vào chỗ chỉnh sửa, anh chỉ lại thành bấm double chỉ hiện ra chỉnh sửa giúp em nhé! Em vào đươc chỉnh sửa, em chọn Xóa toa/bảng kể, phần mềm báo xóa nhưng em thấy vẫn còn nguyên chưa có xóa?

**Comment by tttoan** [comment]
Done
