### ISSUE TITLE
Upload hình mới

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#21]
Khi upload hình mới những hình nào trùng cho bỏ qua luôn không cần phải xác nhận lại, tại vì trong cùng 1 thư mục quá nhiều hình, thì không thể nào xác nhận lại hết được (bấm mọi tay luôn). Chỉ cần có kế quả VD: Tải lên thành công 610/650 hình, có thể thêm 1 lịch sử upload hình và 1 danh sách ghi ra các hình upload bị lỗi hoặc trùng.

**Comment by tttoan** [comment]
Done
