### ISSUE TITLE
Ngày nhận hàng để trống cho bên em nhập vào

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#23]
![image](https://user-images.githubusercontent.com/49013280/55205928-5d97f800-5207-11e9-8c32-eec7d2077ed3.png)
![image](https://user-images.githubusercontent.com/49013280/55205934-5f61bb80-5207-11e9-8a3d-0f9e43ea18cb.png)
Ngày nhận hàng phải để trống cho bên em nhập vào, chứ không phải để mặc định là ngày e upload hình lên và trong mục Thống kê hóa đơn bị lỗi null, nó không hiện ngày mà em đã chỉnh sửa lại!

**Comment by ntxuan** [comment]
Done
