### ISSUE TITLE
Field NVTT có thể bỏ trống

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#24]
![image](https://user-images.githubusercontent.com/49013280/55206598-a6e94700-5209-11e9-8825-e263eaf30b55.png)
Một số khách hàng mới chưa có nhân viên thị trường nên anh điều chỉnh chỗ này lại giúp em không có NVTT vẫn lưu được.

**Comment by ntxuan** [comment]
Done
