### ISSUE TITLE
Lưu dữ liệu sai cột

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#27]
![image](https://user-images.githubusercontent.com/47171247/55611837-eaffbd00-57b0-11e9-8062-0972a7f8638d.png)

- Dữ liệu khi lưu bị sai cột giữa ngày nhận toa và ngày nhận hàng.
+ Ngày hiển thị trên hình: là ngày nhận hàng nhưng khi nhập lại lưu vào ô ngày nhận toa và ngày nhận hàng lại hiển thị chữ "null"

**Comment by tttoan** [comment]
Done
