### ISSUE TITLE
Form nhập toa thiết kế 1 cửa sổ riêng

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#28]
Thiết kế form nhập toa (điều chỉnh toa) ở 1 cửa sổ riêng hoặc tab riêng cho tiện, hiện tại sau khi nhập xong phải bấm nút "Home" rồi lọc điều kiện mới có thể xem được dữ liệu đã nhập rất bất tiện.

**Comment by tttoan** [comment]
Done
