### ISSUE TITLE
Pending List: Thong Ke Hoa Don

### ISSUE THREAD

**Issue by tttoan** [3t-opensources/DongXanh#3]
1. Xuat excel
2. Mac dinh: ngay nhan tu = 01/thang hien tai && ngay nhan den = ngay cuoi/thang hien tai

**Comment by tttoan** [comment]
2. Mac dinh: ngay nhan tu = 01/thang hien tai && ngay nhan den = ngay cuoi/thang hien tai => DONE

**Comment by ntxuan** [comment]
3. Don gia voi thanh tien dao nguoc

**Comment by tttoan** [comment]
DOne
