### ISSUE TITLE
Tạo thêm nút hoặc tự động quay lại ở khi chỉnh sửa lại toa hàng trong Báo cáo Thống kê hóa đơn

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#31]
Khi đang xem phần Báo cáo Thống kê hóa đơn, em muốn chỉnh sửa 1 toa hàng nào đó thì nhấp double vào mã khách hàng, sau khi lưu hoặc xóa hóa đơn đó thì phải tự động quay lại Báo cáo Thống kê hóa đơn hoặc tạo thêm 1 nút quay lại. Tại gì lọc dữ liệu khá lâu, mà em muốn xem lại thông tin nhập hoặc hình ảnh, khi xem hoặc sửa xong phải nhấn home để quay lại trang chủ và bắt đầu lọc lại dữ liệu, tốn 1 khoản thời gian khá lâu khi em muốn xử lý từ hóa đơn có vấn đề!!

**Comment by tttoan** [comment]
Support open new tab, done
