### ISSUE TITLE
Xóa toa đã nhập

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#32]
Em vào mục Báo cáo Thống kê hóa đơn xem toa bị trùng do mình chưa fix phần cảnh báo nhập trùng nên em không phát hiện được nhập trùng. Và bây giờ em muốn xóa nhưng toa hàng bị trùng đó thì không thể xóa được, em bấm Xóa toa/bảng kê nhưng vẫn không xóa được!

**Comment by tttoan** [comment]
Done
