### ISSUE TITLE
Còn hình chưa nhập nhưng lại báo hết hình để nhập!

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#33]
![image](https://user-images.githubusercontent.com/49013280/55930163-4f57cc00-5c4a-11e9-8b23-cc027dc5080a.png)
Danh sách hình chưa nhập còn 3 hình (em đã kiểm tra bằng tên hình và đúng là chưa nhập) nhưng vào nhập hóa đơn thì báo hết hình để nhập, mình fix lỗi này giúp, cám ơn.
![image](https://user-images.githubusercontent.com/49013280/55930165-51218f80-5c4a-11e9-9046-67d7f4435622.png)

**Comment by tttoan** [comment]
Em vào mục thêm mới, xem user giữ card nhé
![image](https://user-images.githubusercontent.com/15169518/56076783-157bf680-5dff-11e9-947a-4c070d791be6.png)
