### ISSUE TITLE
Dữ liệu nhập bị sai.

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#34]
![image](https://user-images.githubusercontent.com/49013280/55930281-d4db7c00-5c4a-11e9-93a9-e92e173e9bdd.png)
Sản phẩm này số lượng phải là 1200 (em nhập đúng 1200) mới được 1 thùng nhưng Báo cáo lại hiển thị có 12 và xuất ra file Excel cũng là 12, và giá cũng sai giống vậy luôn!

**Comment by tttoan** [comment]
EM check lại xem bị lỗi hàng loạt hay 1 vài nhé, chương trình hiện giữ nguyên giá trị nhập các field số lượng, số thùng, đg, tt nhé

**Comment by greenfieldssun** [comment]
Dạ, đúng là nó vẫn giữ nguyên giá trị nhưng hiện thị như vậy là sai rồi anh (phải hiện thị đúng số lượng là 1200, giá cũng vậy), với lại khi xuất ra file Excel nó hiện thị y hệt trong Báo cáo nghĩ là số lượng 12 chứ không phải 1200 như em đã nhập.

**Comment by dthphuongdx** [comment]
Đúng thật chỗ này đang bị hiển thị sai đó Toàn ơi, số lượng và đơn giá khi lưu nó đều bị mất số 0
![image](https://user-images.githubusercontent.com/47171247/56193202-4ad05080-605a-11e9-8222-db59c3a3e59b.png)

**Comment by tttoan** [comment]
Fixed
