### ISSUE TITLE
Lỗi phát hiện toa trùng lập vẫn còn.

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#35]
Em thấy anh đã fix xong rồi nhưng, em nhập cũng thử vài toa thì thấy vẫn còn lỗi. Em nhập toa với nội dung như sau:
![image](https://user-images.githubusercontent.com/49013280/56113256-89e1a180-5f87-11e9-93bc-297b053e3367.png)
Nhưng lại báo trùng trong khi đó em vào kiểm tra trong Thống kê hoa đơn thì không thấy toa nào giống vậy mà vẫn bị cảnh báo là nhập trùng
![image](https://user-images.githubusercontent.com/49013280/56113321-b3023200-5f87-11e9-92b3-0ec7983033ae.png)

Cái này khi còn nhập ở Excel thì làm làm như sau: tạo ra 1 cột dùng hàng CONCATENATE(ngày nhận hàng, mã KH, mã sản phẩm, số lượng). Theo như dữ liệu trên thì nó sẽ thành kết quả: 43563DN020BI15W2120
Khi trong cùng 1 cột có 2 dòng dữ liệu giống y hệt này thì sẽ báo đỏ do em chỉnh phát hiện trùng lập, phát hiện trùng thì em xóa đi.

**Comment by tttoan** [comment]
Fixed
