### ISSUE TITLE
"Ngày nhận hàng" và "Ngày Cấp 1 giao toa" phải tách ra thành 2 cột, không thể gộp lại thành 1 được.

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#36]
"Ngày nhận hàng" và "Ngày Cấp 1 giao toa" là 2 cái khách nhau:
 -Ngày nhận hàng để so sánh đối chiếu với bảng kê
 -Ngày Cấp 1 giao toa là ngày để biết khách nhận hàng trễ từ Cấp 1, không thể áp ngày này vào "Ngày nhận hàng" được, 2 cái đều có chức năng riêng của nói nên mình tách ra 2 cột giúp em.

Nếu "Ngày Cấp 1 giao toa" trống không có dữ liệu thì Số ngày gửi trễ = "Ngày Cty nhận toa" - " Ngày nhận hàng" để ra số ngày gửi trễ. Còn "Ngày Cấp 1 giao toa" có dữ liệu thì Số ngày gửi trễ = "Ngày Cty nhận toa" - "Ngày Cấp 1 giao toa"

**Comment by tttoan** [comment]
Hi em, hien tai ctrinh tach rieng thanh 3 thong tin nhu tren: Ngày nhận hàng + Ngày Cấp 1 giao toa + Ngày cty nhan toa, trong cac report ctrinh chua thay su dung "Ngày cấp 1 giao toa"
Anh chua rõ cau hỏi của em lắm.

**Comment by greenfieldssun** [comment]
Dạ, trong phần nhập thì mình có:
-Ngày nhận hàng
-Ngày công ty nhận toa
-Ngày cấp 1 giao toa
Nhưng trong Report chỉ có 2:
-Ngày nhận hàng
-Ngày công ty nhận toa
Em muốn anh thêm "Ngày cấp 1 giao toa" vào Report luôn giúp em!

**Comment by tttoan** [comment]
Updated
