### ISSUE TITLE
Chỉnh tiêu đề menu "Hóa đơn"

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#37]
- Chỉnh tên menu
+ Hóa đơn -> Toa khách gửi
+ Thêm mới -> Import hình toa
+ Thống kê hóa đơn -> Thống kê toa nhập
+ Thêm menu "Import toa từ excel" (đem phần import bảng kê cấp 2 ở trên xuống) để có thể import những toa đã nhập bằng excel, hoặc bảng kê cấp 2 cũ trước đây

- Chỉnh tên tab "Thống kê hóa đơn" -> Chi tiết toa

![image](https://user-images.githubusercontent.com/47171247/56178519-c2878680-602c-11e9-9cd3-57e52bcff2dc.png)

**Comment by tttoan** [comment]
Phase nay ko support import bang ke tu file excel nha chi, xong roi tinh tiep
Rename menu done
