### ISSUE TITLE
Xuất dữ liệu toa đã nhập ra excel rất lâu.

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#38]
Hiện tại dữ liệu nhập chưa nhiều nhưng khi xuất toa ra excel nó chạy rất lâu. Nhờ em kiểm tra và cải thiện giúp tình trạng này,

**Comment by dthphuongdx** [comment]
Mỗi lần xuất toa đã nhập ra mất gần 2 tiếng đồng hồ file mới được xuất ra.

**Comment by tttoan** [comment]
Fixed
