### ISSUE TITLE
Cập nhật thông tin nhân viên cho phép sữa đổi tên tài khoản

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#39]
Tên tài khoản mặc định theo cấu trúc: viết tắt họ_viết tắt chữ lót_tên đầy đủ
VD: Nguyễn Hữu Thành -> NHThành

Hiện tại tên NVTT không đồng nhất, lúc vầy lúc khác nhưng không thể điều chỉnh được. 
![image](https://user-images.githubusercontent.com/47171247/56180434-89064980-6033-11e9-9d0a-46a31cb1510b.png)

**Comment by dthphuongdx** [comment]
Đồng bồ tất cả thông tin có tên NVTT là: 
1. thanhnh -> NHThành
2. NPDang -> NPĐằng
3. CDNang -> CĐNăng

Cho phép Edit Tên tài khoản của nhân viên thị trường (Hiện tại đang bị khóa chức năng edit cho field này hình ở trên)

**Comment by tttoan** [comment]
Chi Phuong, ten TK duoc dung lam khoa link qua cac table khac nen khong edit dc nhe chi.
