### ISSUE TITLE
Trả job (hình nhập) khi đăng xuất khỏi phần nhập toa

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#40]
Khi Phượng thoát khỏi phần nhập toa thì những hình đã giữ phải được nhả ra để nhân viên khác có thể get job và nhập tiếp.

![image](https://user-images.githubusercontent.com/47171247/56188737-751d1080-6050-11e9-8292-fb2183a61f2c.png)

**Comment by tttoan** [comment]
Nhấn vào button Thoát
