### ISSUE TITLE
Report thống kê/Mặt hàng cấp 1

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#41]
Ý nghĩa các cột như sau:

- Tên cấp 1 là duy nhất không lập lại (hiện tại đang bị lập lại)
- Tổng KH có theo dõi: đếm số lượng khách hàng theo cấp 1 tương ứng của danh sách phân công.
- Tổng KH có gửi toa: đếm không trùng số khách có chụp hình gửi toa theo cấp 1 tương ứng.
- % Toa gửi hợp lệ: tổng số toa gửi trễ >2 ngày chia tổng số toa đã gửi (làm tròn số không hiển thị số lẻ)
- Số thùng: hiện tại đang lấy theo số lượng nên chỗ này bị sai.

![image](https://user-images.githubusercontent.com/47171247/56192425-8702b180-6058-11e9-97f3-0a10f8bb0433.png)

**Comment by tttoan** [comment]
Done
