### ISSUE TITLE
Phân quyền NVTT được xem thống kê hóa đơn

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#42]
Bật quyền NVTT được xem phần thống kê hóa đơn ở 2 tab:
- Thống kê hóa đơn, không được quyền sửa toa
- Tổng hợp theo toa cấp 2

Tuy nhiên chỉ xem số liệu thống kê của những khách hàng do NVTT đăng nhập quản lý thôi không xem số liệu khách hàng của NVTT khác.

**Comment by tttoan** [comment]
Updated
