### ISSUE TITLE
Lỗi trong mục chỉnh sửa Toa hàng.

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#45]
Khi em vào Thống kê hóa đơn để tìm sửa 1 Toa hàng bị sai thì em click double và Mã khách hàng để hiện lên bảng chỉnh sửa, em chỉ sửa những mục cần thiết rồi bấm lưu nhưng dữ liệu vẫn y nguyên như cũ không có thay đổi.
Khi chỉnh sửa số lượng thì số thùng không thay đổi. 
Khi nhập mã sản phẩm thì em bấm Enter thì nó sẽ ra tên sản phẩm, xong bấm thêm 1 lần nữa để qua ô kế tiếp thì nó không hoạt động.
Chức năng thêm 1 dòng mới tròng mục chỉnh sửa cũng không hoạt động luôn, thêm được nhưng điền dữ liệu không được.

**Comment by tttoan** [comment]
Truong hop nay em press F5 refresh page lai nhe
