### ISSUE TITLE
Lỗi điều chỉnh toa vẫn còn

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#48]
Anh có thể tham khảo toa hàng 18/03/2019 của KH DN025, mặc dù đã bấm Refresh rồi như khi em xóa đi 5 thùng CY25E1 thì vẫn không lưu dữ liệu được.

**Comment by greenfieldssun** [comment]
Thêm 1 ví dụ nữa là 29/03/2019 em mún thêm vào 5 thùng AP40E2, mặc dù trước khi chỉnh đã Refresh rồi mà khi lưu dữ liệu vẫn y hệt như cũ.

**Comment by tttoan** [comment]
Fixed
