### ISSUE TITLE
Lỗi điều chỉnh toa hàng bị mất dữ liệu.

### ISSUE THREAD

**Issue by greenfieldssun** [3t-opensources/DongXanh#49]
![image](https://user-images.githubusercontent.com/49013280/56631241-a9ab5080-667e-11e9-9feb-4603c9e52567.png)
Em có điều chỉnh thêm 40 chai DO48S3 vào toa hàng này nhưng, sau khi lưu lại, em vào kiểm tra thì toa trống trơn (em vẫn chưa điều chỉnh, anh có thể vào để tham khảo).
![image](https://user-images.githubusercontent.com/49013280/56631273-ca73a600-667e-11e9-88e0-e690c7fe99b6.png)

**Comment by tttoan** [comment]
Fixed
