### ISSUE TITLE
Thiếu field "Ngày nhận hàng"

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#5]
Field "Ngày nhận hàng" là field bắt buộc nhập, là ngày xuất toa trên phiếu giao hàng.

Thường cấp 1 xuất phiếu và giao hàng cùng ngày nên mặc định field "Ngày cấp 1 giao toa" = "", tuy nhiên nếu cấp 1 xuất trước và giao toa sau thì sẽ nhập thêm "Ngày cấp 1 giao toa" và tính ngày gửi toa trễ từ ngày cấp 1 giao toa.

Nếu field "Ngày cấp 1 giao toa" có nhập giá trị thì: Số ngày gửi trễ = Ngày Cty nhận toa – Ngày cấp 1 giao toa.

**Comment by tttoan** [comment]
Done
