### ISSUE TITLE
Bổ sung chức năng báo cáo định kỳ mỗi ngày tiến độ nhập toa

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#50]
Theo yêu cầu của ban lãnh đạo mỗi ngày cần nắm tiến độ nhập toa của ngày trước đó nên nhờ Toàn bổ sung thêm 1 mẫu báo cáo như sau với yêu cầu như sau:
- Định kỳ trước 8h sáng mỗi ngày sẽ có email tự động gửi báo cáo đến những nhân viên có quyền là "Leader" trong danh sách nhân viên.
- Tiêu đề email báo cáo: Báo cáo tiến độ nhập toa ngày ....... (VD: ngày 24/04/2019)
- Đính kèm báo cáo là file excel với các nội dung sau:
+ Ngày báo cáo: là ngày hiện tại
+ Ngày nhập toa: = ngày hiện tại - 1
+ Tổng doanh số: = tổng doanh số theo ngày nhập toa
+ Chi tiết toa được sắp xếp theo thứ tự giảm dần của **tổng thành tiền cả toa** (không phải theo thành tiền của từng mặt hàng).
![image](https://user-images.githubusercontent.com/47171247/56640937-5812be00-669e-11e9-9871-4c3716c0d77c.png)

**Comment by tttoan** [comment]
Chi cung cap thong tin mail server + account su dung de gui mail nhe:
+ IP/host
+ Port
+ Account mail
+ Password mail

**Comment by dthphuongdx** [comment]
![image](https://user-images.githubusercontent.com/47171247/58307139-f02fce80-7e27-11e9-937e-8a05fe1c1356.png)
Nhờ em chỉnh lại 1 số điểm của báo cáo gửi email hằng ngày như sau:
**1. STT:** Tăng số thứ tự khi bắt đầu 1 toa mới, còn những mặt hàng trong cùng 1 toa không cần đánh số thứ tự.
**2. Thống nhất tên Cấp 1:** yêu cầu này P có nhờ em cập nhật lại cho đúng theo danh sách hoặc chỉ P cách cập nhật nhưng tới giờ vẫn chưa khắc phục. Hiện tại không có cấp 1 nào tên "Đào Nguyên" cả nhưng không biết làm sao để P có thể tự sửa lỗi này và còn 1 số tên cấp 1 khác nữa chưa thống nhất.
**3. Tên NVTT:** hiện tại có 1 số tên NVTT cũng không theo cấu trúc, có cách nào cho P chỉnh lại tất cả được không? VD: NPDang -> NPĐằng, thanhnh -> NHThành mới đúng
**4. Thành tiền:**
- Bỏ giúp đơn vị tiền tệ VNĐ 
- Xem lại cách format số (sao lúc dấu chấm . lúc thì dấu phẩy ,) tùm lum hết vậy? Chỉ cần hiển thị dấu phân cách phần nghìn là dấu phẩy thôi. VD: 2 thùng Cyrux 480ml sẽ có thành tiền là: **4,820,000**
--



-

**Comment by dthphuongdx** [comment]
Tên cấp 1 cần điều chỉnh thống nhất:


Cấp 1   hiện tại | Điều chỉnh
-- | --
CH   Số 1 | DNTN Phạm   Hùng
Công   Ty TNHH Toàn Phát Lộc | Toàn Phát   Lộc
Cty   TNHH Phát Thành | Phát Thành
CTY   TNHH TOÀN PHÁT LỘC | Toàn Phát   Lộc
Đào   Nguyên | Đào Nguyễn
DNTN   Tư Tình | Tư Tình
Nguyễn   Thị Thanh Hà | Lộc Hà
Nguyễn   Văn Bé Ba | Bé Ba
Trần   Hoàng Nam | Nam Tùng
Trịnh   Phú Cường | Thái Cường

**Comment by dthphuongdx** [comment]
Form báo cáo hiện tại chưa gửi mỗi ngày, em kiểm tra lại giúp P và set gửi cho 3 email sau:
- suu.lv@dongxanhvn.com
- nung.pv@dongxanhvn.com
- phuong.dth@dongxanhvn.com

*** Thêm cột group Tổng doanh số theo từng Cấp 1, và sort theo thứ tự giảm dần của Tổng doanh số này.** 

![image](https://user-images.githubusercontent.com/47171247/58772363-c5d9d000-85e2-11e9-9993-8e906af50321.png)

**Comment by tttoan** [comment]
Done
