### ISSUE TITLE
Phân quyền nhập toa

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#51]
- Quyền member (NVTT) chỉ được xem phần thống kê toa, không cho vào import hình toa và nhập hóa đơn. Toàn điều chỉnh lại này giúp.

**Comment by ntxuan** [comment]
xong roi nhe anh

**Comment by dthphuongdx** [comment]
Hiện tại NVTT vẫn có quyền giữ job nhập toa, Xuân kiểm tra lại giúp P.

![image](https://user-images.githubusercontent.com/47171247/60062995-83a93780-9725-11e9-97d8-3978a17869b6.png)
