### ISSUE TITLE
Hiện tại NVTT vẫn có quyền giữ job nhập toa, Xuân kiểm tra lại giúp P.

### ISSUE THREAD

**Issue by dthphuongdx** [3t-opensources/DongXanh#57]
Hiện tại NVTT vẫn có quyền giữ job nhập toa, Xuân kiểm tra lại giúp P.

![image](https://user-images.githubusercontent.com/47171247/60062995-83a93780-9725-11e9-97d8-3978a17869b6.png)

_Originally posted by @dthphuongdx in https://github.com/3t-opensources/DongXanh/issues/51#issuecomment-505243787_

**Comment by tttoan** [comment]
Fixed
